modLoader = "javafml"
loaderVersion="[35,)"
license="Custom"
logoFile="pack.png"
logoBlur=false

[[mods]]
modId="spawnanimations"
version="${version}+mod"
displayName="Spawn Animations"
description='''Hostile mobs dig out of the ground or poof into existence when they spawn!

§lWorks with:§r Zombies, Husks, Drowned, Skeletons, Strays, Spiders, Cave Spiders, Creepers, Slimes, Magma Cubes, Wither Skeletons, Hoglins, Zombified Piglins, Striders, Enderman and Giants.

This data pack is designed to be as unintrusive as possible. Hidden entities including their worn armor and tools will only be invisible and silent.

Execute the command §o/function §ospawnanimations:settings§r for a world-specific settings menu and/or install MidnightLib for global settings accross all worlds.
'''
authors="Tschipcraft"
displayURL="https://tschipcraft.ddns.net/spawnanimations.html"
issueTrackerURL="https://github.com/Tschipcraft/spawnanimations/issues"
updateJSONURL="https://api.modrinth.com/updates/zrzYrlm0/forge_updates.json"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.spawnanimations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spawnanimations]]
    modId="midnightlib"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"

[modproperties.spawnanimations]
    catalogueItemIcon="minecraft:zombie_spawn_egg"